version: '2'

services:
  nginx:
    image: bitnami/nginx:1.10.2-r1
    volumes:
      - ./config/nginx:/bitnami/nginx/conf/vhosts
    depends_on:
      - backend
      - frontend
    environment:
      - VIRTUAL_HOST=yourproject.docker
      - VIRTUAL_PORT=8080
    ports:
      - 8080:8080
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=backend_development
  backend:
    build: backend
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/backend-app
  frontend:
    build:
      context: ./frontend/
    depends_on:
      - backend
    command: npm start
    volumes:
      - ./frontend/:/usr/src/frontend-app
      - /usr/src/frontend-app/node_modules
    ports:
      - "35729:35729"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=true